Repository elastic/elastic-agent-client, pull requests merged in 2020-05, with the labels that each got.

#1 Initial client
  LICENSE.txt
  elastic-agent-client.pb.go
  elastic-agent-client.proto
  go.mod
  go.sum
  magefile.go
Labels: Team:Ingest Management

#3 chore: add a bot that labels any PR with the team label
  .github/paths-labeller.yml
Labels: Team:Ingest Management

#4 Add a client implementation to communicate with Elastic Agent.
  .gitignore
  elastic-agent-client.proto
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/proto/elastic-agent-client.pb.go
  pkg/utils/utils.go
Labels: Team:Ingest Management, [zube]: In Review

#5 Add `client.NewFromReader` that creates a new client from reading bytes from the reader.
  elastic-agent-client.proto
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/reader.go
  pkg/client/reader_test.go
  pkg/proto/elastic-agent-client.pb.go
Labels: Team:Ingest Management

#7 ci: job for build and test on the CI
  .ci/Jenkinsfile
  .ci/jenkins-go-agent/Dockerfile
  .ci/jobs/defaults.yml
  .ci/jobs/elastic-agent-client.yml
Labels: ci, team:automation

#8 ci: Change the way to launch Docker containers
  .ci/Jenkinsfile
  .ci/jenkins-go-agent/Dockerfile
Labels: bug, ci, team:automation
